version: "3.8"

services:
  turbo:
    container_name: payment-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3005:3005"
      - "3006:3006"

    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - common-network



networks:
  common-network:
    driver: bridge
    name: "common"

