version: "3.8"

services:
  turbo:
    image: arunshaik2001/paymnt-app:docker
    container_name: paymnt-app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3005:3005"
      - "3006:3006"

    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
    name: "common"
