name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: arunshaik2001/paymnt-app:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}

    - name: Verify Pushed Image
      run: docker pull arunshaik2001/paymnt-app:latest 

    - name: Create dir in Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Create composefiles directory if it doesn't exist
          mkdir -p "$HOME/composefiles"
          # Create or update the .env file with DATABASE_URL
          touch "$HOME/composefiles/.env"
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > "$HOME/composefiles/.env"


    - name: Copy docker-compose file to Server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.paymnt.yml"
        target: "$HOME/composefiles/"

    # - name: run docker-compose
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |

    #       # Navigate to the composefiles directory and run docker-compose in detached mode
    #       cd "$HOME/composefiles"
    #       docker pull arunshaik2001/paymnt-app:latest
    #       docker stop paymnt-app || true
    #       docker rm paymnt-app || true
    #       docker create network common
    #       docker run -d --name paymnt-app -p 3000:3000 -p 3001:3001 -p 3005:3005 -p 3006:3006 --env-file ./.env arunshaik2001/paymnt-app:latest